### ISSUE TITLE
GitHub API Token

### ISSUE THREAD

**Issue by TrevorS** [kostajh/dotfiles#1]
Hello Kosta, how are you?

I'd recommend against including your GitHub API token in [.vimrc](https://github.com/kostajh/dotfiles/blob/5bd261c9b440b45288b2d872a210e38282f24c7f/.vimrc).  You should invalidate this token ASAP. The key you've included allows anybody to perform (possibly bad) actions as you.

https://help.github.com/articles/creating-an-access-token-for-command-line-use

**Comment by kostajh** [comment]
... oops! Thanks.
